name: Bug report
description: File a bug/issue
title: "BUG | short description of your bug"
labels: [ bug ]
body:
  - type: markdown
    attributes:
      value: "## Welcome! Is there an existing issue for this?"
  - type: markdown
    attributes:
      value: "### Please search to see if an issue already exists for the bug you encountered."
  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: false
  - type: input
    attributes:
      label: OS
      description: What operating system are you using?
      placeholder: ex. Windows 10
    validations:
      required: true
  - type: input
    attributes:
      label: OS Version
      description: What version of the operating system are you using?
      placeholder: ex. 20H2
    validations:
      required: false
  - type: input
    attributes:
      label: AMRPC Version
      description: What version of AMRPC are you using?
      placeholder: ex. 4.0.0
    validations:
      required: true
  - type: dropdown
    attributes:
      label: AMRPC Mode
      options:
        - iTunes
        - Apple Music
      default: 1
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!
        
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
        
        *[How do I find the log file?](https://github.com/ZephraCloud/Apple-Music-RPC/wiki/Creating-a-bug-report#how-do-i-find-the-log-file)*
    validations:
      required: false
